import { useState } from 'react';
// import Barn from './comps/barn';
import ItemCard from './comps/itemCard';
// import Silo from './comps/silo';
import TruckOrder from './comps/truck-order';
import Inventory from './comps/inventory';
import './output.css';

function App() {


  const [Db, setDb] = useState([
    { 
      id: 1,
      level: 1,
      name: "wheat",
      needs: { "wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Wheat.webp",
      count: 0,
    },
    { 
      id: 2,
      level: 1,
      name: "egg",
      needs: { "chickenfeed": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Egg.webp",
      count: 0,
    },
    { 
      id: 3,
      level: 2,
      name: "corn",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Corn.webp",
      count: 0,
    },
    { 
      id: 4,
      level: 2,
      name: "bread",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Bread.webp",
      count: 0,
    },
    { 
      id: 5,
      level: 3,
      name: "chicken feed",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Chicken_Feed.webp",
      count: 0,
    },
    { 
      id: 6,
      level: 5,
      name: "soybean",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Soybean.webp",
      count: 0,
    },
    { 
      id: 7,
      level: 6,
      name: "cow feed",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cow_Feed.webp",
      count: 0,
    },
    { 
      id: 8,
      level: 6,
      name: "milk",
      needs: { "cowfeed": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Milk.webp",
      count: 0,
    },

    { 
      id: 9,
      level: 6,
      name: "cream",
      needs: { "milk": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cream.webp",
      count: 0,
    },
    { 
      id: 10,
      level: 7,
      name: "sugarcane",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Sugarcane.webp",
      count: 0,
    },
    { 
      id: 11,
      level: 7,
      name: "corn bread",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Corn_Bread.webp",
      count: 0,
    },
    { 
      id: 12,
      level: 7,
      name: "brown sugar",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Brown_Sugar.webp",
      count: 0,
    },
    { 
      id: 13,
      level: 8,
      name: "popcorn",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Popcorn.webp",
      count: 0,
    },
    { 
      id: 14,
      level: 9,
      name: "carrot",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Carrot.webp",
      count: 0,
    },
    { 
      id: 15,
      level: 1,
      name: "butter",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Butter.webp",
      count: 0,
    },
    { 
      id: 16,
      level: 1,
      name: "pancake",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Pancake.webp",
      count: 0,
    },

    { 
      id: 17,
      level: 1,
      name: "pig feed",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Pig_Feed.webp",
      count: 0,
    },
    { 
      id: 18,
      level: 1,
      name: "bacon",
      needs: { "pigfeed": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Bacon.webp",
      count: 0,
    },
    { 
      id: 19,
      level: 1,
      name: "cookie",
      needs: { "": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cookie.webp",
      count: 0,
    },
    { 
      id: 20,
      level: 1,
      name: "bacon and eggs",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Bacon_and_Eggs.webp",
      count: 0,
    },
    { 
      id: 21,
      level: 1,
      name: "cheese",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cheese.webp",
      count: 0,
    },
    { 
      id: 22,
      level: 1,
      name: "indigo",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Indigo.webp",
      count: 0,
    },
    { 
      id: 23,
      level: 1,
      name: "carrot pie",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Carrot_Pie.webp",
      count: 0,
    },
    { 
      id: 24,
      level: 1,
      name: "pumpkin",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Pumpkin.webp",
      count: 0,
    },

    { 
      id: 25,
      level: 1,
      name: "pumpkin pie",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Pumpkin_Pie.webp",
      count: 0,
    },
    { 
      id: 26,
      level: 1,
      name: "apple",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Apple.webp",
      count: 0,
    },
    { 
      id: 27,
      level: 1,
      name: "sheep feed",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Sheep_Feed.webp",
      count: 0,
    },
    { 
      id: 28,
      level: 1,
      name: "wool",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Wool.webp",
      count: 0,
    },
    { 
      id: 29,
      level: 1,
      name: "buttered popcorn",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Buttered_Popcorn.webp",
      count: 0,
    },
    { 
      id: 30,
      level: 1,
      name: "sweater",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Sweater.webp",
      count: 0,
    },
    { 
      id: 31,
      level: 1,
      name: "cotton",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cotton.webp",
      count: 0,
    },
    { 
      id: 32,
      level: 1,
      name: "bacon pie",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Bacon_Pie.webp",
      count: 0,
    },

    { 
      id: 33,
      level: 1,
      name: "syrup",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Syrup.webp",
      count: 0,
    },
    { 
      id: 34,
      level: 1,
      name: "cotton fabric",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cotton_Fabric.webp",
      count: 0,
    },
    { 
      id: 35,
      level: 1,
      name: "hamburger",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Hamburger.webp",
      count: 0,
    },
    { 
      id: 36,
      level: 1,
      name: "raspberry",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Raspberry.webp",
      count: 0,
    },
    { 
      id: 37,
      level: 1,
      name: "raspberry muffin",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Raspberry_Muffin.webp",
      count: 0,
    },
    { 
      id: 38,
      level: 1,
      name: "blue woolly hat",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Blue_Woolly_Hat.webp",
      count: 0,
    },
    { 
      id: 39,
      level: 1,
      name: "cotton shirt",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cotton_Shirt.webp",
      count: 0,
    },
    { 
      id: 40,
      level: 1,
      name: "blue sweater",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Blue_Sweater.webp",
      count: 0,
    },

    { 
      id: 41,
      level: 1,
      name: "carrot cake",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Carrot_Cake.webp",
      count: 0,
    },
    { 
      id: 42,
      level: 1,
      name: "wooly chaps",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Wooly_Chaps.webp",
      count: 0,
    },
    { 
      id: 43,
      level: 1,
      name: "cherry",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cherry.webp",
      count: 0,
    },
    { 
      id: 44,
      level: 1,
      name: "cream cake",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cream_Cake.webp",
      count: 0,
    },
    { 
      id: 45,
      level: 1,
      name: "red berry cake",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Red_Berry_Cake.webp",
      count: 0,
    },
    { 
      id: 46,
      level: 1,
      name: "cheesecake",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cheesecake.webp",
      count: 0,
    },
    { 
      id: 47,
      level: 1,
      name: "silver ore",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Silver_Ore.webp",
      count: 0,
    },
    { 
      id: 48,
      level: 1,
      name: "gold ore",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Gold_Ore.webp",
      count: 0,
    },
    { 
      id: 49,
      level: 1,
      name: "platinum ore",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Platinum_Ore.webp",
      count: 0,
    },
    { 
      id: 50,
      level: 1,
      name: "silver bar",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Silver_Bar.webp",
      count: 0,
    },
    { 
      id: 51,
      level: 1,
      name: "chili pepper",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Chili_Pepper.webp",
      count: 0,
    },

    { 
      id: 52,
      level: 1,
      name: "chili popcorn",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Chili_Popcorn.webp",
      count: 0,
    },
    { 
      id: 53,
      level: 1,
      name: "gold bar",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Gold_Bar.webp",
      count: 0,
    },
    { 
      id: 54,
      level: 1,
      name: "platinum bar",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Platinum_Bar.webp",
      count: 0,
    },
    { 
      id: 55,
      level: 1,
      name: "violet dress",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Violet_Dress.webp",
      count: 0,
    },
    { 
      id: 56,
      level: 1,
      name: "blackberry",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Blackberry.webp",
      count: 0,
    },
    { 
      id: 57,
      level: 1,
      name: "blackberry muffin",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Blackberry_Muffin.webp",
      count: 0,
    },
    { 
      id: 58,
      level: 1,
      name: "carrot juice",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Carrot_Juice.webp",
      count: 0,
    },
    { 
      id: 59,
      level: 1,
      name: "fish fillet",
      needs: { "lure or fishing net": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Fish_Fillet.webp",
      count: 0,
    },

    { 
      id: 60,
      level: 1,
      name: "fish burger",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Fish_Burger.webp",
      count: 0,
    },
    { 
      id: 61,
      level: 1,
      name: "apple pie",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Apple_Pie.webp",
      count: 0,
    },
    { 
      id: 62,
      level: 1,
      name: "fish pie",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Fish_Pie.webp",
      count: 0,
    },
    { 
      id: 63,
      level: 1,
      name: "apple juice",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Apple_Juice.webp",
      count: 0,
    },
    { 
      id: 64,
      level: 1,
      name: "vanilla ice cream",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Vanilla_Ice_Cream.webp",
      count: 0,
    },
    { 
      id: 65,
      level: 1,
      name: "tomato",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Tomato.webp",
      count: 0,
    },
    { 
      id: 66,
      level: 1,
      name: "roasted tomatoes",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Roasted_Tomatoes.webp",
      count: 0,
    },
    { 
      id: 67,
      level: 1,
      name: "cherry juice",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cherry_Juice.webp",
      count: 0,
    },

    { 
      id: 68,
      level: 1,
      name: "fishing net",
      needs: {},
      source: "Field",
      max_price: 3,
      icon: "./icons/Fishing_Net.webp",
      count: 0,
    },
    { 
      id: 69,
      level: 1,
      name: "mystery net",
      needs: { "diamond": 5 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Mystery_Net.webp",
      count: 0,
    },
    { 
      id: 70,
      level: 1,
      name: "tomato juice",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Tomato_Juice.webp",
      count: 0,
    },
    { 
      id: 71,
      level: 1,
      name: "berry juice",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Berry_Juice.webp",
      count: 0,
    },
    { 
      id: 72,
      level: 1,
      name: "goat feed",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Goat_Feed.webp",
      count: 0,
    },
    { 
      id: 73,
      level: 1,
      name: "goat milk",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Goat_Milk.webp",
      count: 0,
    },
    { 
      id: 74,
      level: 1,
      name: "goat cheese",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Goat_Cheese.webp",
      count: 0,
    },
    { 
      id: 75,
      level: 1,
      name: "pizza",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Pizza.webp",
      count: 0,
    },

    { 
      id: 76,
      level: 1,
      name: "coal",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Coal.webp",
      count: 0,
    },
    { 
      id: 77,
      level: 1,
      name: "refined coal",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Refined_Coal.webp",
      count: 0,
    },
    { 
      id: 78,
      level: 1,
      name: "cherry popsicle",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cherry_Popsicle.webp",
      count: 0,
    },
    { 
      id: 79,
      level: 1,
      name: "strawberry",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Strawberry.webp",
      count: 0,
    },
    { 
      id: 80,
      level: 1,
      name: "feta pie",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Feta_Pie.webp",
      count: 0,
    },
    { 
      id: 81,
      level: 1,
      name: "iron ore",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Iron_Ore.webp",
      count: 0,
    },
    { 
      id: 82,
      level: 1,
      name: "iron bar",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Iron_Ore.webp",
      count: 0,
    },
    { 
      id: 83,
      level: 1,
      name: "strawberry ice cream",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Strawberry_Ice_Cream.webp",
      count: 0,
    },

    { 
      id: 84,
      level: 1,
      name: "wheat bundle",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Wheat_Bundle.webp",
      count: 0,
    },
    { 
      id: 85,
      level: 1,
      name: "meat bucket",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Meat_Bucket.webp",
      count: 0,
    },
    { 
      id: 86,
      level: 1,
      name: "potato",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Potato.webp",
      count: 0,
    },
    { 
      id: 87,
      level: 1,
      name: "strawberry cake",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Strawberry_Cake.webp",
      count: 0,
    },
    { 
      id: 88,
      level: 1,
      name: "baked potato",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Baked_Potato.webp",
      count: 0,
    },
    { 
      id: 89,
      level: 1,
      name: "apple jam",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Apple_Pie.webp",
      count: 0,
    },
    { 
      id: 90,
      level: 1,
      name: "cacao",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cacao.webp",
      count: 0,
    },
    { 
      id: 91,
      level: 1,
      name: "chocolate cake",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Chocolate_Cake.webp",
      count: 0,
    },
    { 
      id: 92,
      level: 1,
      name: "casserole",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Casserole.webp",
      count: 0,
    },
    { 
      id: 93,
      level: 1,
      name: "raspberry jam",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Raspberry_Jam.webp",
      count: 0,
    },
    { 
      id: 94,
      level: 1,
      name: "spicy pizza",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Spicy_Pizza.webp",
      count: 0,
    },
    { 
      id: 95,
      level: 1,
      name: "blackberry jam",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Blackberry_Jam.webp",
      count: 0,
    },
    { 
      id: 96,
      level: 1,
      name: "potato feta cake",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Potato_Feta_Cake.webp",
      count: 0,
    },
    { 
      id: 97,
      level: 1,
      name: "cherry jam",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Cherry_Jam.webp",
      count: 0,
    },
    { 
      id: 98,
      level: 1,
      name: "bracelet",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Bracelet.webp",
      count: 0,
    },
    { 
      id: 99,
      level: 1,
      name: "potato bread",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Potato_Bread.webp",
      count: 0,
    },

    { 
      id: 100,
      level: 1,
      name: "shepherd's pie",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Shepherd's_Pie.webp",
      count: 0,
    },
    { 
      id: 101,
      level: 1,
      name: "chocolate ice cream",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Chocolate_Ice_Cream.webp",
      count: 0,
    },
    { 
      id: 102,
      level: 1,
      name: "honeycomb",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Honeycomb.webp",
      count: 0,
    },
    { 
      id: 103,
      level: 1,
      name: "necklace",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Necklace.webp",
      count: 0,
    },
    { 
      id: 104,
      level: 1,
      name: "honey",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Honey.webp",
      count: 0,
    },
    { 
      id: 105,
      level: 1,
      name: "diamond ring",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Diamond_Ring.webp",
      count: 0,
    },
    { 
      id: 106,
      level: 1,
      name: "fish and chips",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Fish_and_Chips.webp",
      count: 0,
    },
    { 
      id: 107,
      level: 1,
      name: "iron bracelet",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Iron_Bracelet.webp",
      count: 0,
    },

    { 
      id: 108,
      level: 1,
      name: "coffee bean",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Coffee_Bean.webp",
      count: 0,
    },
    { 
      id: 109,
      level: 1,
      name: "espresso",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Espresso.webp",
      count: 0,
    },
    { 
      id: 110,
      level: 1,
      name: "honey apple cake",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Honey_Apple_Cake.webp",
      count: 0,
    },
    { 
      id: 111,
      level: 1,
      name: "caffe latte",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Caff__Latte.webp",
      count: 0,
    },
    { 
      id: 112,
      level: 1,
      name: "chocolate popcorn",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Chocolate_Popcorn.webp",
      count: 0,
    },
    { 
      id: 113,
      level: 1,
      name: "lobster trap",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Lobster_Trap.webp",
      count: 0,
    },
    { 
      id: 114,
      level: 1,
      name: "lobster tail",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Lobster_Tail.webp",
      count: 0,
    },
    { 
      id: 115,
      level: 1,
      name: "frutti di mare pizza",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Frutti_di_Mare_Pizza.webp",
      count: 0,
    },

    { 
      id: 116,
      level: 1,
      name: "caffe mocha",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Caff__Mocha.webp",
      count: 0,
    },
    { 
      id: 117,
      level: 1,
      name: "chamomile",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Chamomile.webp",
      count: 0,
    },
    { 
      id: 118,
      level: 1,
      name: "soothing pad",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Soothing_Pad.webp",
      count: 0,
    },
    { 
      id: 119,
      level: 1,
      name: "raspberry mocha",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Raspberry_Mocha.webp",
      count: 0,
    },
    { 
      id: 120,
      level: 1,
      name: "lobster soup",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Lobster_Soup.webp",
      count: 0,
    },
    { 
      id: 121,
      level: 1,
      name: "hot chocolate",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Hot_Chocolate.webp",
      count: 0,
    },
    { 
      id: 122,
      level: 1,
      name: "red scarf",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Red_Scarf.webp",
      count: 0,
    },
    { 
      id: 123,
      level: 1,
      name: "lobster skewer",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Lobster_Skewer.webp",
      count: 0,
    },

    { 
      id: 124,
      level: 1,
      name: "beeswax",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Beeswax.webp",
      count: 0,
    },
    { 
      id: 125,
      level: 1,
      name: "strawberry candle",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Strawberry_Candle.webp",
      count: 0,
    },
    { 
      id: 126,
      level: 1,
      name: "rustic bouquet",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Rustic_Bouquet.webp",
      count: 0,
    },
    { 
      id: 127,
      level: 1,
      name: "pumpkin soup",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Pumpkin_Soup.webp",
      count: 0,
    },
    { 
      id: 128,
      level: 1,
      name: "asparagus",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Asparagus.webp",
      count: 0,
    },
    { 
      id: 129,
      level: 1,
      name: "asparagus quiche",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Asparagus_Quiche.webp",
      count: 0,
    },
    { 
      id: 130,
      level: 1,
      name: "strawberry jam",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Strawberry_Jam.webp",
      count: 0,
    },
    { 
      id: 131,
      level: 1,
      name: "duck trap",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Duck_Trap.webp",
      count: 0,
    },

    { 
      id: 132,
      level: 1,
      name: "duck feather",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Duck_Feather.webp",
      count: 0,
    },
    { 
      id: 133,
      level: 1,
      name: "sesame",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Sesame.webp",
      count: 0,
    },
    { 
      id: 134,
      level: 1,
      name: "sesame ice cream",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Sesame_Ice_Cream.webp",
      count: 0,
    },
    { 
      id: 135,
      level: 1,
      name: "caramel apple",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Caramel_Apple.webp",
      count: 0,
    },
    { 
      id: 136,
      level: 1,
      name: "pillow",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Pillow.webp",
      count: 0,
    },
    { 
      id: 137,
      level: 1,
      name: "asparagus soup",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Asparagus_Soup.webp",
      count: 0,
    },
    { 
      id: 138,
      level: 1,
      name: "toffee",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Toffee.webp",
      count: 0,
    },
    { 
      id: 139,
      level: 1,
      name: "raspberry candle",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Raspberry_Candle.webp",
      count: 0,
    },
    { 
      id: 140,
      level: 1,
      name: "pineapple",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Pineapple.webp",
      count: 0,
    },
    { 
      id: 141,
      level: 1,
      name: "pineapple juice",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Pineapple_Juice.webp",
      count: 0,
    },
    { 
      id: 142,
      level: 1,
      name: "fish soup",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Fish_Soup.webp",
      count: 0,
    },
    { 
      id: 143,
      level: 1,
      name: "lily",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Lily.webp",
      count: 0,
    },
    { 
      id: 144,
      level: 1,
      name: "soy souce",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Soy_Sauce.webp",
      count: 0,
    },
    { 
      id: 145,
      level: 1,
      name: "chocolate",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Chocolate.webp",
      count: 0,
    },
    { 
      id: 146,
      level: 1,
      name: "fancy cake",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Fancy_Cake.webp",
      count: 0,
    },
    { 
      id: 147,
      level: 1,
      name: "rice",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Rice.webp",
      count: 0,
    },
    { 
      id: 148,
      level: 1,
      name: "sushi roll",
      needs: { "Wheat": 1 },
      source: "Field",
      max_price: 3,
      icon: "./icons/Sushi_Roll.webp",
      count: 0,
    },
  ]);

  const [needDb, setNeedDb] = useState([]);

  const [inventoryDb, setinventoryDb] = useState([]);

  const incrementCount = (id) => {
    const newDb = Db.map((product) => {
      if (product.id === id) {
        return {
          ...product,
          count: product.count + 1
        };
      }
      return product;
    });
    setDb(newDb);
  };

  const decrementCount = (id) => {
    const newDb = Db.map((product) => {
      if (product.id === id) {
        return {
          ...product,
          count: product.count - 1
        };
      }
      return product;
    });
    setDb(newDb);
  };

  const removeProduct = (id) => {
    const newDb = Db.map((product) => {
      if (product.id === id) {
        return {
          ...product,
          count: 0
        };
      };
      return product;
    });
    setDb(newDb);

    const newNeedDb = needDb.map((product) => {
      if (product.id === id) {
        return {
          ...product,
          count: 0
        };
      };
      return product;
    });
    setNeedDb(newNeedDb);
  };

  return (

    <div className='text-indigo-950 bg-slate-100 rounded-lg'>

      <div className='flex flex-row'> 
        <div className='flex flex-row flex-wrap justify-center w-1/2'> 

          {Db.map((product) =>
            <ItemCard className='flex flex-row'
              key={product.id}
              incrementCount={() => incrementCount(product.id)}
              icon_File={product.icon}
              count={product.count}
              name={product.name}
              decrementCount={() => decrementCount(product.id)}
              removeProduct={() => removeProduct(product.id)}
            />
          )}

        </div>

        <div className='flex flex-row flex-wrap justify-center w-1/2'> 

          {needDb.map((product) =>
            <ItemCard className='flex flex-row'
              key={product.id}
              icon_File={product.icon}
              count={product.count}
              name={product.name}
            />
          )}

        </div>

      </div>

    </div>
  );
}

export default App;
